name: hugo-deploy

on:
  push:
    branches:
      - master

env:
  TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #  HUGO_ARGS: '--minify'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: 🛎 Check out master
        uses: actions/checkout@main
        with:
          fetch-depth: 1
      - name: 🚀 Build and deploy
        uses: LFrakie/parsa-hugo@main
